In [95]:
# !pip install pydotplus --user

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from IPython.display import Image
from sklearn.tree import export_graphviz
# import pydotplus
from sklearn import preprocessing
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn import preprocessing
from sklearn.model_selection import cross_val_score,StratifiedKFold
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score,StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from IPython.display import Image
from sklearn.tree import export_graphviz
from sklearn import preprocessing

In [41]:
featuresNuevas = pd.read_csv('features_generadas.csv')
users = pd.read_pickle('users.pkl')

In [43]:
users = users[~users.id.isna()]
users = users[['id', 'Cat', 'default_profile', 'description', 'geo_enabled', 'lang', 'listed_count', 'location', 'name', 'profile_background_color', 'profile_background_image_url', 'profile_background_image_url_https', 'profile_background_tile', 'profile_banner_url', 'profile_image_url', 'profile_image_url_https', 'profile_link_color', 'profile_sidebar_border_color', 'profile_sidebar_fill_color', 'profile_text_color', 'profile_use_background_image', 'screen_name', 'url','favs_tiempo','followers_tiempo', 'statuses_tiempo','friends_tiempo']]
display(users.head())
print(users.columns)

,id,Cat,default_profile,description,geo_enabled,lang,listed_count,location,name,profile_background_color,...,profile_sidebar_border_color,profile_sidebar_fill_color,profile_text_color,profile_use_background_image,screen_name,url,favs_tiempo,followers_tiempo,statuses_tiempo,friends_tiempo
0,24858289,SocialSpambot1,1.0,True,True,True,0,False,True,True,...,True,True,True,True,True,False,0.062251,1.369531,80.864594,2.490057
1,33212890,SocialSpambot1,0.0,True,True,True,110,True,True,True,...,True,True,True,True,True,True,1020.440156,783.576770,1164.354781,214.717876
2,39773427,SocialSpambot1,0.0,True,False,True,6,True,True,True,...,True,True,True,True,True,False,0.887230,38.024155,1456.768757,47.847062
3,57007623,SocialSpambot1,0.0,True,False,True,2,True,True,True,...,True,True,True,True,True,False,0.719522,26.033600,521.653169,22.893869
4,63258466,SocialSpambot1,0.0,True,True,True,8,True,True,True,...,True,True,True,True,True,True,10.775305,27.470376,1344.784653,26.938262

Index(['id', 'Cat', 'default_profile', 'description', 'geo_enabled', 'lang',
       'listed_count', 'location', 'name', 'profile_background_color',
       'profile_background_image_url', 'profile_background_image_url_https',
       'profile_background_tile', 'profile_banner_url', 'profile_image_url',
       'profile_image_url_https', 'profile_link_color',
       'profile_sidebar_border_color', 'profile_sidebar_fill_color',
       'profile_text_color', 'profile_use_background_image', 'screen_name',
       'url', 'favs_tiempo', 'followers_tiempo', 'statuses_tiempo',
       'friends_tiempo'],
      dtype='object')

In [44]:
display(featuresNuevas.head())
print(featuresNuevas.columns)

,user_id,user_id.1,bot,Cat,tweetsCount,semanas,lun,mar,mie,jue,...,num_mentions_mean,num_mentions_median,num_mentions_std,num_mentions_fq,num_mentions_tq,reply_count_mean,reply_count_median,reply_count_std,reply_count_fq,reply_count_tq
0,678033.0,678033.0,False,Humans,3195,27,20.560000,24.320000,19.560000,18.200000,...,9019.780220,10000.0,8720.070307,0.0,10000.0,0.0,0.0,0.0,0.0,0.0
1,722623.0,722623.0,False,Humans,3201,89,6.678571,5.069767,6.321429,5.602273,...,5439.727066,0.0,6453.941616,0.0,10000.0,0.0,0.0,0.0,0.0,0.0
2,755116.0,755116.0,False,Humans,3209,30,11.423077,16.666667,18.464286,31.448276,...,9337.349398,10000.0,10512.287386,0.0,20000.0,0.0,0.0,0.0,0.0,0.0
3,755746.0,755746.0,False,Humans,3234,91,5.046512,5.227273,6.726190,5.116279,...,6102.096011,10000.0,6578.193523,0.0,10000.0,0.0,0.0,0.0,0.0,0.0
4,785080.0,785080.0,False,Humans,3235,23,24.000000,19.285714,27.047619,31.631579,...,7184.534271,10000.0,8842.028988,0.0,10000.0,0.0,0.0,0.0,0.0,0.0

Index(['user_id', 'user_id.1', 'bot', 'Cat', 'tweetsCount', 'semanas', 'lun',
       'mar', 'mie', 'jue', 'vie', 'sab', 'dom', 'times_mean', 'times_median',
       'times_std', 'times_fq', 'times_tq', 'timesRT_mean', 'timesRT_median',
       'timesRT_std', 'timesRT_fq', 'timesRT_tq', 'timesUser_mean',
       'timesUser_median', 'timesUser_std', 'timesUser_fq', 'timesUser_tq',
       'favorite_count_mean', 'favorite_count_median', 'favorite_count_std',
       'favorite_count_fq', 'favorite_count_tq', 'retweet_count_mean',
       'retweet_count_median', 'retweet_count_std', 'retweet_count_fq',
       'retweet_count_tq', 'num_mentions_mean', 'num_mentions_median',
       'num_mentions_std', 'num_mentions_fq', 'num_mentions_tq',
       'reply_count_mean', 'reply_count_median', 'reply_count_std',
       'reply_count_fq', 'reply_count_tq'],
      dtype='object')

In [45]:
len(featuresNuevas), len(users)

(5995, 5995)

In [49]:
usuariosFinal = users.merge(featuresNuevas, left_on='id', right_on='user_id', how='inner')
print(len(usuariosFinal))
display(usuariosFinal.head())
print(usuariosFinal.columns)

5995

,id,Cat_x,default_profile,description,geo_enabled,lang,listed_count,location,name,profile_background_color,...,num_mentions_mean,num_mentions_median,num_mentions_std,num_mentions_fq,num_mentions_tq,reply_count_mean,reply_count_median,reply_count_std,reply_count_fq,reply_count_tq
0,24858289,SocialSpambot1,1.0,True,True,True,0,False,True,True,...,513.330680,0.0,2242.982991,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,33212890,SocialSpambot1,0.0,True,True,True,110,True,True,True,...,7415.023080,0.0,10489.220051,0.0,10000.0,0.0,0.0,0.0,0.0,0.0
2,39773427,SocialSpambot1,0.0,True,False,True,6,True,True,True,...,839.251130,0.0,2920.646061,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,57007623,SocialSpambot1,0.0,True,False,True,2,True,True,True,...,5815.041382,0.0,9024.184195,0.0,10000.0,0.0,0.0,0.0,0.0,0.0
4,63258466,SocialSpambot1,0.0,True,True,True,8,True,True,True,...,3031.628533,0.0,5588.401791,0.0,10000.0,0.0,0.0,0.0,0.0,0.0

Index(['id', 'Cat_x', 'default_profile', 'description', 'geo_enabled', 'lang',
       'listed_count', 'location', 'name', 'profile_background_color',
       'profile_background_image_url', 'profile_background_image_url_https',
       'profile_background_tile', 'profile_banner_url', 'profile_image_url',
       'profile_image_url_https', 'profile_link_color',
       'profile_sidebar_border_color', 'profile_sidebar_fill_color',
       'profile_text_color', 'profile_use_background_image', 'screen_name',
       'url', 'favs_tiempo', 'followers_tiempo', 'statuses_tiempo',
       'friends_tiempo', 'user_id', 'user_id.1', 'bot', 'Cat_y', 'tweetsCount',
       'semanas', 'lun', 'mar', 'mie', 'jue', 'vie', 'sab', 'dom',
       'times_mean', 'times_median', 'times_std', 'times_fq', 'times_tq',
       'timesRT_mean', 'timesRT_median', 'timesRT_std', 'timesRT_fq',
       'timesRT_tq', 'timesUser_mean', 'timesUser_median', 'timesUser_std',
       'timesUser_fq', 'timesUser_tq', 'favorite_count_mean',
       'favorite_count_median', 'favorite_count_std', 'favorite_count_fq',
       'favorite_count_tq', 'retweet_count_mean', 'retweet_count_median',
       'retweet_count_std', 'retweet_count_fq', 'retweet_count_tq',
       'num_mentions_mean', 'num_mentions_median', 'num_mentions_std',
       'num_mentions_fq', 'num_mentions_tq', 'reply_count_mean',
       'reply_count_median', 'reply_count_std', 'reply_count_fq',
       'reply_count_tq'],
      dtype='object')

In [106]:
# featuresNuevas = featuresNuevas.fillna(0)
print(len(featuresNuevas.columns) - 6)
featuresNuevas.columns

42

Index(['user_id', 'user_id.1', 'bot', 'Cat', 'tweetsCount', 'semanas', 'lun',
       'mar', 'mie', 'jue', 'vie', 'sab', 'dom', 'times_mean', 'times_median',
       'times_std', 'times_fq', 'times_tq', 'timesRT_mean', 'timesRT_median',
       'timesRT_std', 'timesRT_fq', 'timesRT_tq', 'timesUser_mean',
       'timesUser_median', 'timesUser_std', 'timesUser_fq', 'timesUser_tq',
       'favorite_count_mean', 'favorite_count_median', 'favorite_count_std',
       'favorite_count_fq', 'favorite_count_tq', 'retweet_count_mean',
       'retweet_count_median', 'retweet_count_std', 'retweet_count_fq',
       'retweet_count_tq', 'num_mentions_mean', 'num_mentions_median',
       'num_mentions_std', 'num_mentions_fq', 'num_mentions_tq',
       'reply_count_mean', 'reply_count_median', 'reply_count_std',
       'reply_count_fq', 'reply_count_tq'],
      dtype='object')

In [87]:
X = pd.get_dummies(featuresNuevas.drop(['user_id', 'user_id.1', 'bot', 'Cat', 'tweetsCount', 'semanas'], axis=1))
atributos = X.columns
X = preprocessing.scale(X, axis = 0)
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(featuresNuevas['bot'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

from sklearn.tree import DecisionTreeClassifier
treeclf = DecisionTreeClassifier(max_depth=5, random_state=1)
treeclf.fit(X_train, y_train)
pd.DataFrame({'Atributo':atributos,
              'importancia':treeclf.feature_importances_}).sort_values('importancia',
                                                                      ascending=False).head(20)

                Atributo  importancia
11              times_tq     0.502867
4                    vie     0.110522
6                    dom     0.089770
0                    lun     0.087789
16            timesRT_tq     0.064694
1                    mar     0.062185
5                    sab     0.040445
7             times_mean     0.022400
31      retweet_count_tq     0.004969
2                    mie     0.003349
28  retweet_count_median     0.003333
10              times_fq     0.002341
21          timesUser_tq     0.001807
27    retweet_count_mean     0.001186
25     favorite_count_fq     0.001173
32     num_mentions_mean     0.001169
8           times_median     0.000000
40        reply_count_fq     0.000000
39       reply_count_std     0.000000
38    reply_count_median     0.000000

In [89]:
from sklearn.metrics import confusion_matrix
conf = confusion_matrix(y_test, treeclf.predict(X_test))


predicted_cols = ['pred_'+str(c) for c in le.classes_]


pd.DataFrame(conf, index = le.classes_, columns = predicted_cols)

       pred_False  pred_True
False         221         85
True           49       1444

In [90]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
param_trees = {'n_estimators': [50, 100, 200], 
               'max_features': [1, 5, 8, 10, 21], 
               'max_depth': [5, 20, 50, 70, 100], 
               'min_samples_leaf':[1, 5, 8, 10, 50]}

In [96]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(class_weight='balanced')
kf = StratifiedKFold(n_splits=3, shuffle=True)
grid_search_rf = GridSearchCV(rf, param_grid=param_trees, cv=kf, verbose=1, n_jobs=-1)

In [97]:
grid_search_rf.fit(X_train, y_train)

Fitting 3 folds for each of 375 candidates, totalling 1125 fits

[Parallel(n_jobs=-1)]: Done  26 tasks      | elapsed:    7.8s
[Parallel(n_jobs=-1)]: Done 176 tasks      | elapsed:   15.3s
[Parallel(n_jobs=-1)]: Done 426 tasks      | elapsed:   36.4s
[Parallel(n_jobs=-1)]: Done 776 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 1125 out of 1125 | elapsed:  1.7min finished

GridSearchCV(cv=StratifiedKFold(n_splits=3, random_state=None, shuffle=True),
       error_score='raise',
       estimator=RandomForestClassifier(bootstrap=True, class_weight='balanced',
            criterion='gini', max_depth=None, max_features='auto',
            max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=-1,
       param_grid={'n_estimators': [50, 100, 200], 'max_features': [1, 5, 8, 10, 21], 'max_depth': [5, 20, 50, 70, 100], 'min_samples_leaf': [1, 5, 8, 10, 50]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=1)

In [98]:
model = grid_search_rf.best_estimator_
grid_search_rf.best_score_

0.9559103908484271

In [99]:
# Predecir valores de test
y_pred = model.predict(X_test)
# Calculamos el accuracy general del modelo
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9566425792106726

In [100]:
conf = confusion_matrix(y_test, y_pred)


predicted_cols = ['pred_'+str(c) for c in le.classes_]


pd.DataFrame(conf, index = le.classes_, columns = predicted_cols)

       pred_False  pred_True
False         259         47
True           31       1462

In [108]:
pd.DataFrame({'Atributo':atributos,
              'importancia':model.feature_importances_}).sort_values('importancia',
                                                                      ascending=False)

                 Atributo  importancia
5                     sab     0.167556
16             timesRT_tq     0.090214
11               times_tq     0.084091
7              times_mean     0.066895
6                     dom     0.047360
0                     lun     0.045336
1                     mar     0.041841
12           timesRT_mean     0.038714
24     favorite_count_std     0.036674
4                     vie     0.036084
3                     jue     0.035916
9               times_std     0.026982
29      retweet_count_std     0.024598
21           timesUser_tq     0.021494
20           timesUser_fq     0.020123
17         timesUser_mean     0.019572
18       timesUser_median     0.018750
2                     mie     0.018705
19          timesUser_std     0.018615
33    num_mentions_median     0.015822
31       retweet_count_tq     0.013998
13         timesRT_median     0.013642
14            timesRT_std     0.013525
26      favorite_count_tq     0.012084
23  favorite_count_median     0.011697
28   retweet_count_median     0.011474
8            times_median     0.009927
10               times_fq     0.009900
30       retweet_count_fq     0.005423
22    favorite_count_mean     0.004954
27     retweet_count_mean     0.004207
25      favorite_count_fq     0.003895
15             timesRT_fq     0.003403
35        num_mentions_fq     0.003038
32      num_mentions_mean     0.002767
34       num_mentions_std     0.000471
36        num_mentions_tq     0.000251
37       reply_count_mean     0.000000
38     reply_count_median     0.000000
39        reply_count_std     0.000000
40         reply_count_fq     0.000000
41         reply_count_tq     0.000000

In [129]:
from sklearn.preprocessing import StandardScaler

dfSin3 = featuresNuevas[featuresNuevas.Cat!='SocialSpambot3']

X = pd.get_dummies(dfSin3.drop(['user_id', 'user_id.1', 'bot', 'Cat', 'tweetsCount', 'semanas'], axis=1))
atributos = X.columns
# X = preprocessing.scale(X, axis = 0)

le = LabelEncoder()
y = le.fit_transform(dfSin3['bot'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
param_trees = {'n_estimators': [200, 300], 
               'max_features': [21, 30, 40], 
               'max_depth': [100], 
               'min_samples_leaf':[1, 5, 8, 10, 50]}

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(class_weight='balanced')
kf = StratifiedKFold(n_splits=3, shuffle=True)
grid_search_rf = GridSearchCV(rf, param_grid=param_trees, cv=kf, verbose=1, n_jobs=-1)


X_train

array([[-0.22369404, -0.11100922, -0.02081904, ...,  0.        ,
         0.        ,  0.        ],
       [-0.207393  , -0.10596359, -0.0212963 , ...,  0.        ,
         0.        ,  0.        ],
       [-0.13675516, -0.10932735, -0.01974522, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.21146826, -0.10091795, -0.02153492, ...,  0.        ,
         0.        ,  0.        ],
       [-0.23184456, -0.09587231, -0.02189286, ...,  0.        ,
         0.        ,  0.        ],
       [-0.13977387, -0.10783235, -0.01772149, ...,  0.        ,
         0.        ,  0.        ]])

In [130]:
grid_search_rf.fit(X_train, y_train)

Fitting 3 folds for each of 30 candidates, totalling 90 fits

[Parallel(n_jobs=-1)]: Done  26 tasks      | elapsed:   10.6s
[Parallel(n_jobs=-1)]: Done  90 out of  90 | elapsed:   37.4s finished

GridSearchCV(cv=StratifiedKFold(n_splits=3, random_state=None, shuffle=True),
       error_score='raise',
       estimator=RandomForestClassifier(bootstrap=True, class_weight='balanced',
            criterion='gini', max_depth=None, max_features='auto',
            max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=-1,
       param_grid={'n_estimators': [200, 300], 'max_features': [21, 30, 40], 'max_depth': [100], 'min_samples_leaf': [1, 5, 8, 10, 50]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=1)

In [131]:
model = grid_search_rf.best_estimator_
print('best score', grid_search_rf.best_score_)

# Predecir valores de test
y_pred = model.predict(X_test)
# Calculamos el accuracy general del modelo
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

best score 0.9855334538878843

0.9879518072289156

In [138]:
dfBot3 = featuresNuevas[featuresNuevas.Cat=='SocialSpambot3']
y_test3 = le.transform(dfBot3.bot)
x_test3 = pd.get_dummies(dfBot3.drop(['user_id', 'user_id.1', 'bot', 'Cat', 'tweetsCount', 'semanas'], axis=1))
x_test3 = scaler.transform(x_test3)

y_pred3 = model.predict(x_test3)
print(accuracy_score(y_test3, y_pred3))

conf = confusion_matrix(y_test3, y_pred3)
pd.DataFrame(conf, index = le.classes_, columns = predicted_cols)

0.07543103448275862

       pred_False  pred_True
False           0          0
True          429         35

In [139]:
from sklearn.linear_model  import LogisticRegression
from sklearn.model_selection import GridSearchCV

logistic =  LogisticRegression()
hyperparameters = {'C': np.logspace(0, 4, 50), 
                   'penalty': ['l1', 'l2']}

clasificador = GridSearchCV(logistic, hyperparameters, cv=5, verbose=0)
best_model = clasificador.fit(X_train, y_train)

In [141]:
print('Mejor PenalizaciÃ³n:', best_model.best_estimator_.get_params()['penalty'])
print('Mejor C:', best_model.best_estimator_.get_params()['C'])

Mejor PenalizaciÃ³n: l1
Mejor C: 1.2067926406393286

In [149]:
# Predecir valores de test
y_pred = best_model.predict(X_test)
# Calculamos el accuracy general del modelo
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

conf = confusion_matrix(y_test, y_pred)
pd.DataFrame(conf, index = le.classes_, columns = predicted_cols)

0.9771084337349397

       pred_False  pred_True
False         340         23
True           15       1282

In [144]:
y_pred3 = best_model.predict(x_test3)
print(accuracy_score(y_test3, y_pred3))

conf = confusion_matrix(y_test3, y_pred3)
pd.DataFrame(conf, index = le.classes_, columns = predicted_cols)

0.9547413793103449

       pred_False  pred_True
False           0          0
True           21        443

In [148]:
 featuresNuevas.groupby('Cat').count()

,user_id,user_id.1,bot,tweetsCount,semanas,lun,mar,mie,jue,vie,...,num_mentions_mean,num_mentions_median,num_mentions_std,num_mentions_fq,num_mentions_tq,reply_count_mean,reply_count_median,reply_count_std,reply_count_fq,reply_count_tq
Cat,,,,,,,,,,,,,,,,,,,,,
Humans,1083,1083,1083,1083,1083,1083,1083,1083,1083,1083,...,1083,1083,1083,1083,1083,1083,1083,1083,1083,1083
SocialSpambot1,991,991,991,991,991,991,991,991,991,991,...,991,991,991,991,991,991,991,991,991,991
SocialSpambot2,3457,3457,3457,3457,3457,3457,3457,3457,3457,3457,...,3457,3457,3457,3457,3457,3457,3457,3457,3457,3457
SocialSpambot3,464,464,464,464,464,464,464,464,464,464,...,464,464,464,464,464,464,464,464,464,464